/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.MC;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import MC.classes.Reportdesign;
import clasess.DBconnecter;



/**
 *
 * @author Dineth
 */
public class mediStatement extends javax.swing.JFrame {

    /**
     * Creates new form DrugStatementInt
     */
    public mediStatement() {
        initComponents();
        fillCombo();
        jTextField1.setText("0");
        setLocationRelativeTo(null);
    }
    
     private void fillCombo() {
         DBconnecter db = new DBconnecter();
        Connection con = db.getConnection();
        String sql = "select * from medicine";
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                jComboBox2.addItem(rs.getString(3));
                jComboBox1.addItem(rs.getString(1));
            }
            stmt.close();
            con.close();
        } catch (Exception ex) {

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UWU MEDICAL CENTER");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton1.setText("Finish Drugs");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton2.setText("Expire Drugs");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton3.setText("Available Drugs");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton4.setText("Expire nearly");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioButton5.setText("Quantity ");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Drug ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Drug Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("From");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("To");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("d-MM-yyyy");
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jDateChooser2.setDateFormatString("d-MM-yyyy");
        jDateChooser2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouses/medistateme128.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Medicine Statement ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jRadioButton5)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton4)
                                        .addComponent(jRadioButton3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton1))))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButton1))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    
    private int getNum(){
        if(jRadioButton1.isSelected()){
            return 1;
        }else if(jRadioButton2.isSelected()){
            return 2;
        }else if(jRadioButton3.isSelected()){
            return 3;
        }else if(jRadioButton4.isSelected()){
            return 4;
        }else if(jRadioButton5.isSelected()){
            return 5;
        }else{
            return 6;
        }
    }
    
    
    
    Reportdesign rd=new Reportdesign();
    DBconnecter con=new DBconnecter();
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String q=jTextField1.getText();
        int quantity=Integer.parseInt(q);
        DBconnecter db=new DBconnecter();
        Connection con=db.getConnection();
        String n=jComboBox1.getSelectedItem().toString();
        int mNo=Integer.parseInt(n);
        String reportSource = "/MC/reports/all_drug_stock.jrxml";
        try{
        switch(getNum()){
            case 1:
                
            String sql1="SELECT\n" +
            "     medical_store.`sId` AS medical_store_sId,\n" +
            "     medical_store.`mNo` AS medical_store_mNo,\n" +
            "     medical_store.`mName` AS medical_store_mName,\n" +
            "     medical_store.`quantity` AS medical_store_quantity,\n" +
            "     medical_store.`manufacturer` AS medical_store_manufacturer,\n" +
            "     medical_store.`eDate` AS medical_store_eDate,\n" +
            "     medical_store.`sDate` AS medical_store_sDate,\n" +
            "     medical_store.`mDate` AS medical_store_mDate\n" +
            "FROM\n" +
            "     `medical_store` medical_store where medical_store.`quantity`=0 and medical_store.`eDate`>=curdate() order by medical_store.`mNo`";    
                
           
             
                
            rd.getReport(reportSource, con, sql1);    
                
                break;
                
            case 2:
                
                
                
            String sql2="SELECT\n" +
            "     medical_store.`sId` AS medical_store_sId,\n" +
            "     medical_store.`mNo` AS medical_store_mNo,\n" +
            "     medical_store.`mName` AS medical_store_mName,\n" +
            "     medical_store.`quantity` AS medical_store_quantity,\n" +
            "     medical_store.`manufacturer` AS medical_store_manufacturer,\n" +
            "     medical_store.`eDate` AS medical_store_eDate,\n" +
            "     medical_store.`sDate` AS medical_store_sDate,\n" +
            "     medical_store.`mDate` AS medical_store_mDate\n" +
            "FROM\n" +
            "     `medical_store` medical_store where medical_store.`eDate`<=curdate() and medical_store.`quantity`>0 order by medical_store.`mNo`";    
              
             
            rd.getReport(reportSource, con, sql2);
            
                break;
                
            case 3:
                
                String sql3="SELECT\n" +
            "     medical_store.`sId` AS medical_store_sId,\n" +
            "     medical_store.`mNo` AS medical_store_mNo,\n" +
            "     medical_store.`mName` AS medical_store_mName,\n" +
            "     medical_store.`quantity` AS medical_store_quantity,\n" +
            "     medical_store.`manufacturer` AS medical_store_manufacturer,\n" +
            "     medical_store.`eDate` AS medical_store_eDate,\n" +
            "     medical_store.`sDate` AS medical_store_sDate,\n" +
            "     medical_store.`mDate` AS medical_store_mDate\n" +
            "FROM\n" +
            "     `medical_store` medical_store where medical_store.`mNo`="+mNo+" order by medical_store.`mNo`";    
                
              
           
       
            rd.getReport(reportSource, con, sql3);
                 
                break;
                
            case 4:
                
                Date d1=jDateChooser1.getDate();
                Date d2=jDateChooser2.getDate();
                String fDate=new SimpleDateFormat("yyyy-MM-dd").format(d1);
                String tDate=new SimpleDateFormat("yyyy-MM-dd").format(d2);
                
                
                String sql4="SELECT\n" +
            "     medical_store.`sId` AS medical_store_sId,\n" +
            "     medical_store.`mNo` AS medical_store_mNo,\n" +
            "     medical_store.`mName` AS medical_store_mName,\n" +
            "     medical_store.`quantity` AS medical_store_quantity,\n" +
            "     medical_store.`manufacturer` AS medical_store_manufacturer,\n" +
            "     medical_store.`eDate` AS medical_store_eDate,\n" +
            "     medical_store.`sDate` AS medical_store_sDate,\n" +
            "     medical_store.`mDate` AS medical_store_mDate\n" +
            "FROM\n" +
            "     `medical_store` medical_store where medical_store.`eDate`>='"+fDate+"' and medical_store.`eDate`<='"+tDate+"'  order by medical_store.`mNo`";    
                
            rd.getReport(reportSource, con, sql4);
            
                break;
                
            case 5:
                
                     
                String sql5="SELECT\n" +
            "     medical_store.`sId` AS medical_store_sId,\n" +
            "     medical_store.`mNo` AS medical_store_mNo,\n" +
            "     medical_store.`mName` AS medical_store_mName,\n" +
            "     medical_store.`quantity` AS medical_store_quantity,\n" +
            "     medical_store.`manufacturer` AS medical_store_manufacturer,\n" +
            "     medical_store.`eDate` AS medical_store_eDate,\n" +
            "     medical_store.`sDate` AS medical_store_sDate,\n" +
            "     medical_store.`mDate` AS medical_store_mDate\n" +
            "FROM\n" +
            "     `medical_store` medical_store where medical_store.`quantity`<="+quantity+"  order by medical_store.`mNo`";    
                
            rd.getReport(reportSource, con, sql5);
            
                break;
                
            default:
                
                JOptionPane.showMessageDialog(null, "please select");
                
                break;
                
        }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String id=jComboBox1.getSelectedItem().toString();
        int n=Integer.parseInt(id);
        DBconnecter db=new DBconnecter();
        Connection con=db.getConnection();
        String sql="select * from medicine where mNo="+n+"";
        try{
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(sql);
        if(rs.next()){
            jComboBox2.setSelectedItem(rs.getString(3));
        }
        stmt.close();
        con.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error", JOptionPane.ERROR);
        }
        
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
         String name=jComboBox2.getSelectedItem().toString();
        
        DBconnecter db=new DBconnecter();
        Connection con=db.getConnection();
        String sql="select * from medicine where mName='"+name+"'";
        try{
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery(sql);
        if(rs.next()){
            jComboBox1.setSelectedItem(rs.getString(1));
        }
        stmt.close();
        con.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error", JOptionPane.ERROR);
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mediStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mediStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mediStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mediStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mediStatement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
